Algoritmo "Pintura"

Var
     altura, largura, area, tinta: real

Inicio
      Escreval("Digite a altura da parede: (m) ")
      Leia (altura)
      Escreval ("Digite a largura da parede: (m) ")
      Leia (largura)
      
area <- altura * largura
tinta <- area/2

   Escreval("A area total do seu espaço é de: ", area:0:2, " m²")
   Escreval ("Quantidade de tinta necessária: ", tinta:0:2, " litros")

   


Fimalgoritmo