algoritmo "salario"
var
       nome, mes: caractere
       sal: real
inicio
      Escreval("Qual é o seu nome?")
      Leia (nome)
      Escreval("Qual o seu salário mensal?")
      Leia(sal)
      Escreval ("O salário é referente a qual mês?")
      Leia(mes)

Escreval("Nome do funcionário(a): ", nome)
Escreval (" Salário Mensal: R$ ", sal)
Escreval ("Mês de Referência: ", mes)
      

fimalgoritmo